server:
  port: 8090
  
spring:
  application:
    name: api-gateway # eureka에 등록되는 service id
    
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

security:
  oauth2:
    client:
      id: auth_id
      client-secret: auth_secret
    resource:
      jwt:
        key-value: jwt_secret_key # authorization server와 동일하게 셋팅해야 함      

zuul:
  ignored-services: '*' # eureka에 등록된 모든 서비스를 zuul은 자동 등록하기 때문에 해당 서비스를 제외시킨다
  routes: # 명시적으로 지정한 서비스만 zuul에 등록
    moim-service: # eureka에 등록된 서비스
      path: /api/moim/** # 경로를 지정
      strip-prefix: false # /api/moim/meet/1 에서 true이면 /api/moim을 제거하고 /meet/1로 보냄 
  sensitive-headers: # routing 되기전에 해당 header를 제거하고 보냄
  - Cookie
  - Set-Cookie